name: 'Compile'
description: 'Compile and compress @tensorflow/tfjs-node for AWS Lambda'
inputs:
  lambda: # id of input
    description: 'The lambda node version'
    required: true
  tensorflow: # id of input
    description: 'The @tensorflow/tfjs-node version'
    required: true
  binary: # id of input
    description: 'The compressed @tensorflow/tfjs-node project root file path'
    required: true

runs:
  using: 'node12'
  main: './dist/index.js'
