name: 'Compile'
description: 'Compile and compress @tensorflow/tfjs-node for AWS Lambda'
inputs:
  lambda: # id of input
    description: 'The lambda node version'
    required: true
  tensorflow: # id of input
    description: 'The @tensorflow/tfjs-node version'
    required: true
outputs:
  asset: # id of output
    description: 'The compiled and compressed @tensorflow/tfjs-node file path'
runs:
  using: 'node12'
  main: 'index.js'
