name: 'Hello World'
description: 'Retrieve matrix of lambda and tensorflow versions'

outputs:
  lambda: # id of output
    description: 'lambci/docker-lambda node versions'
  tensorflow: # id of output
    description: '@tensorflow/tfjs-node versions'
  shouldUpdate: # id of output
    description: 'Whether a new version needs to be published'

runs:
  using: 'node12'
  main: 'index.js'
